############################################################
# Decap CMS configuration for Shusmo Games (Netlify Identity)
############################################################

backend:
  name: git-gateway
  branch: main

# Optional site display name shown in the CMS UI
site_url: https://shusmo.io
logo_url: https://shusmo.io/logo.png

# Media settings (unchanged)
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

collections:
  - name: games
    label: Games
    files:
      - file: "public/games.json"
        label: "Game List"
        name: games_list
        format: json
        fields:
          - label: Games
            name: games
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: Image, name: image, widget: image }
              - { label: Download URL, name: download_url, widget: string }

  - name: settings
    label: Settings
    files:
      - file: "public/contact.json"
        label: "Contact Information"
        name: contact
        format: json
        fields:
          - { label: Email, name: email, widget: string }
          - { label: Phone, name: phone, widget: string, required: false }
          - { label: Address, name: address, widget: text, required: false }
